"""empty message

Revision ID: 96c227e0d552
Revises: 2b499e7f9e55
Create Date: 2023-07-25 13:56:02.437855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c227e0d552'
down_revision = '2b499e7f9e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('eye_color', sa.String(length=80), nullable=True),
    sa.Column('hair_color', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=80), nullable=True),
    sa.Column('terrain', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('planets')
    op.drop_table('vehicles')
    op.drop_table('characters')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])

    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='characters_pkey'),
    sa.UniqueConstraint('name', name='characters_name_key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('crew', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey'),
    sa.UniqueConstraint('name', name='vehicles_name_key')
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('climate', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('terrain', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planets_pkey'),
    sa.UniqueConstraint('name', name='planets_name_key')
    )
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
